---
name: Checks

on: [push]

jobs:

  test-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check that the image builds
        run: docker build . --file Dockerfile

  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - name: Build service s
        run: docker-compose up -d
      - name: List container
        run: docker-compose ps

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run:
          docker-compose up -d
          docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

#      - name: Lint
#        run: docker-compose run --rm app sh -c "flake8"

